### ISSUE TITLE
questions on v0.0.5

### ISSUE THREAD

**Issue by balmas** [fbaumgardt/perseids-annotator#42]
@fbaumgardt some questions and comments that came up as @Marie-ClaireBeaulieu and I looked at the latest version. These may become issues depending upon your answers :)
1. Are the typeahead suggestions for the subject and object only populated by existing annotations? And if so, does it use all annotations, or will it be limited to those owned by the user once the user filtering is reactivated?  I'm concerned about the students getting the identifiers right for things that aren't annotated yet.  Could we provide a source for the typeahead that is preloaded with all the smith uris and all the perseus text uris (for the citations/characterizations)  (and possibly pleaides uris for places) ?
2. For the characterizations, I think we are going to need the ability for the user to enter the text along with the CTS URN/URI of the text in which it occurs. This is because we don't have a nice easy way for them to select that from the source text right now and get it automatically calculated for them as a text selector. (i.e. they'll want an annotation body which is "some descriptive text" from http://data.perseus.org/citations/urn:cts:greekLit:tlg0012.tlg001.perseus-grc1:1.1 ) where "some descriptive text" is expressed as a TextSelector.  Is this already in your plans? (I know characterization support may not be ready yet)
3. The undo feature maybe needs to have some visual indicator that it's working. When I clicked it looked like nothing happened, but then all the widgets disappeared - I think they were being reloaded and I was too impatient to wait.

**Comment by fbaumgardt** [comment]
1. It's currently using a hardcoded list which I plan to replace with a query for existing subjects and objects. [Edit: And yes, we can query for all users' annotations.]
2. Not planned, but possible.
3. Yes, undo is resetting the view, i.e. it resets and reapplies the annotation using an index on the history (which is an array of SPARQL commands). There is a ~1s wait until the new state is rendered. We can add a spinner to communicate that.

**Comment by balmas** [comment]
Ok, I think I will enter 3 issues for these then.  For the first, I think we need to be able to load in an extra list because for new annotations the users aren't necessarily going to to know what to enter for the people identifiers.  We had actually talked about displaying this in the view, but I'm not sure it is the best approach. Ultimately we want to be able to pull in this data from other sources, anyway, for example we'd like to be able to use abbreviations for the texts, etc.

**Comment by balmas** [comment]
See #43, #44 and #45 :)
