### ISSUE TITLE
make sure the edit button is always visible in the popup

### ISSUE THREAD

**Issue by balmas** [fbaumgardt/perseids-annotator#51]
it is being hidden by the scrollbars right now.

It might also be good to make the popup expandable, so that people can increase its size if they want.

**Comment by fbaumgardt** [comment]
Scrollbars should be gone now as per the CSS edit in the commit above.

**Comment by fbaumgardt** [comment]
Re: resizable popover: http://jqueryui.com/resizable/

**Comment by fbaumgardt** [comment]
@balmas Given that the scrollbars are removed, resizable popovers are now a feature and non-critical. I'll open another issue and add it to a later milestone.
